# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.tapscan:
        container_name: tapscan_v4_laravel
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        ports:
             - '8000:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
            - './_data:/data'
        networks:
            - sail
        depends_on:
            - mysql.tapscan
        healthcheck:
          test: ["CMD", 'curl', 'http://localhost:80/about']

    mysql.tapscan:
        image: mysql:8.0
        container_name: tapscan_v4_mysql
        ports:
            - '3307:3306'
        command:
            - '--local_infile=1'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
