#! /bin/bash

# edit the tree files to include NCBI taxIDs
# this will enhance the tree images generated by ETE toolkit (etetoolkit.org) as generated in the svgs folder
# MAP Ids using OMA API https://omabrowser.org/api/genome/<UniprotID>/
# fasta files are named with this uniprot ID


for i in ../fasta/*.fa
do
  # parse the genome code from the fasta files
  uniprot_code=$(basename $i)
  uniprot_code=${uniprot_code%.fa}
  echo $uniprot_code

  # get the corresponding NCBI_taxon name
  ncbi=$(curl -s https://omabrowser.org/api/genome/$uniprot_code/ | jq '.taxon_id')
  echo $ncbi

done
